version: '2'
services:
  web:
    container_name: web
    build: cos4cloud-front
    command: npm run start
    ports:
      - "3333:3333"
    environment:
      HOST: https://europe-west2-cos4cloud-2d9d3.cloudfunctions.net
      NATUSFERA: https://natusfera.gbif.es
  mapping:
    container_name: mapping
    build: cos4cloud
    command: npm run start
    ports:
      - "10010:10010"
